Expose a property that allows to enabled the old JVM backend.
tschuchortdev/kotlin-compile-testing pull request #127
Opened 2021-03-15 00:57 UTC by vRallev

That flag needs to be set to true with Kotlin 1.5.0 in order to use the old backend. The `useIr` property became a no-op.

See also: https://github.com/JetBrains/kotlin/blob/1.5.0-M1/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/jvmArguments.kt#L195-L200

2021-03-15 10:51 UTC, tschuchortdev requested changes
Is it not enough to set `useIR = false`? I suppose we should stick to the Kotlinc API even if it feels wrong to me to have two options that do the same thing, one of which doesn't work. But we should at least have a `@Deprecated` warning on `useIR` with a note to use `useOldBackend` instead. It may also be helpful to update the default value of the `useIR` property for documentation even though it has no effect.

2021-03-15 15:05 UTC, vRallev commented
> Is it not enough to set `useIR = false`?

No, that's why I added the link to the new if check. I also asked the same question in the [Kotlin Slack channel](https://kotlinlang.slack.com/archives/C01KWTRVA69/p1615770884013200).

> I suppose we should stick to the Kotlinc API even if it feels wrong to me to have two options that do the same thing, one of which doesn't work. 

That was my thinking initially. But at the same time I wouldn't mind using only the `useIR` field. That would make the API surface for your compile testing library easier to understand and there would be no difference between Kotlin versions. I'm now more leaning towards this solution. What do you think? 

I would not deprecate the `useIR` field, yet. Kotlin `1.5.0` is still in preview.

2021-03-16 14:45 UTC, vRallev commented
JetBrains confirmed that the extra property is by design and `useIR` will be deprecated:

> It's intentional. We'll deprecate it in 1.5.0. We'd like to get rid of this flag from users' projects as soon as possible, to be able to drop the old backend altogether in a future release.
I've created an issue so that we don't forget to do it: https://youtrack.jetbrains.com/issue/KT-45504

2021-03-20 21:39 UTC, tschuchortdev commented
> I wouldn't mind using only the useIR field. That would make the API surface for your compile testing library easier to understand and there would be no difference between Kotlin versions. I'm now more leaning towards this solution. What do you think?

I'd like to stay close to the kotlinc API for now. In the future there will likely be a simplified API but until then it's probably the least confusing not to deviate too much. I found that most users don't change many options anyway. They just define a `compile` function with their own defaults and then use that everywhere.

> the extra property is by design and useIR will be deprecated

Alright, I'll add the deprecation warning when upgrading to Kotlin 1.5.0 then.

2021-03-20 21:39 UTC, merged